/gate/geometry/setMaterialDatabase ../data/GateMaterials.db 

/gate/world/geometry/setXLength 2. m 
/gate/world/geometry/setYLength 2. m 
/gate/world/geometry/setZLength 2. m 
/gate/world/setMaterial Air 
/gate/world/vis/setVisible 0  

/gate/world/daughters/name CTscanner 
/gate/world/daughters/insert box 
/gate/CTscanner/setMaterial CdTe
/gate/CTscanner/geometry/setXLength 14 mm 
/gate/CTscanner/geometry/setYLength 14 mm 
/gate/CTscanner/geometry/setZLength 1 mm 
/gate/CTscanner/vis/forceSolid 
/gate/CTscanner/vis/setColor yellow 
/gate/CTscanner/placement/setTranslation 0. 0. 7. cm 
//gate/world/daughters/name Phantom
/gate/world/daughters/insert box
/gate/Phantom/placement/setTranslation 0.0 0.0 0. cm 
/gate/Phantom/setMaterial PMMA
/gate/Phantom/geometry/setXLength 2. cm
/gate/Phantom/geometry/setYLength 2. cm
/gate/Phantom/geometry/setZLength 4.62273 cm
/gate/Phantom/vis/forceWireframe
/gate/Phantom/vis/setColor red
/gate/Phantom/vis/setVisible 1 


/gate/physics/addPhysicsList emstandard_opt4 


/gate/actor/addActor DoseActor     MyActor 

/gate/actor/MyActor/save                        MyOutputFileBase10-0.mhd 

/gate/actor/MyActor/attachTo                    CTscanner 
/gate/actor/MyActor/setResolution               254 254 1 
/gate/actor/MyActor/stepHitType                 post 


/control/verbose 0 
/run/verbose 0 
/run/particle/verbose 0 
/event/verbose 0 
/tracking/verbose 0 
/tracking/verbose 0 
/gate/generator/verbose 0 
/gate/source/verbose 0 
/run/particle/verbose 0 

/gate/run/initialize
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/source/addSource electron_beam gps
/gate/source/electron_beam/gps/particle gamma 
/gate/source/electron_beam/gps/ene/type Gauss 


/gate/source/electron_beam/gps/ene/mono 0.016000 MeV 
/gate/source/electron_beam/gps/ene/sigma 0.00216 MeV 
/gate/source/electron_beam/gps/centre 0 0 -63 cm 
/gate/source/electron_beam/gps/angtype iso 
/gate/source/electron_beam/gps/mintheta 0 deg 
/gate/source/electron_beam/gps/maxtheta 0 deg 
/gate/source/electron_beam/gps/minphi 0 deg 
/gate/source/electron_beam/gps/maxphi 0 deg 
/gate/source/electron_beam/gps/type Plane 
/gate/source/electron_beam/gps/shape Square
/gate/source/electron_beam/gps/halfx 15 mm
/gate/source/electron_beam/gps/halfy 15 mm

/gate/application/setTotalNumberOfPrimaries 1e8 
/gate/application/start 

