/gate/geometry/setMaterialDatabase ../data/GateMaterials.db 

/gate/world/geometry/setXLength 2. m 
/gate/world/geometry/setYLength 2. m 
/gate/world/geometry/setZLength 2. m 
/gate/world/setMaterial Air 
/gate/world/vis/setVisible 0  

/gate/world/daughters/name CTscanner 
/gate/world/daughters/insert box 
/gate/CTscanner/setMaterial CdTe
/gate/CTscanner/geometry/setXLength 14 mm 
/gate/CTscanner/geometry/setYLength 14 mm 
/gate/CTscanner/geometry/setZLength 1 mm 
/gate/CTscanner/vis/forceSolid 
/gate/CTscanner/vis/setColor yellow 
/gate/CTscanner/placement/setTranslation 0. 0. 7. cm 
//gate/world/daughters/name Phantom
/gate/world/daughters/insert box
/gate/Phantom/placement/setTranslation 0.0 0.0 0. cm 
/gate/Phantom/setMaterial PMMA
/gate/Phantom/geometry/setXLength 2. cm
/gate/Phantom/geometry/setYLength 2. cm
/gate/Phantom/geometry/setZLength 4.01 cm
/gate/Phantom/vis/forceWireframe
/gate/Phantom/vis/setColor red
/gate/Phantom/vis/setVisible 1 


/gate/physics/addPhysicsList emstandard_opt4 


/gate/actor/addActor DoseActor     MyActor 

/gate/actor/MyActor/save                        MyOutputFileBase80-6.mhd 

/gate/actor/MyActor/attachTo                    CTscanner 
/gate/actor/MyActor/setResolution               255 255 1 
/gate/actor/MyActor/stepHitType                 post 


/control/verbose 0 
/run/verbose 0 
/run/particle/verbose 0 
/event/verbose 0 
/tracking/verbose 0 
/tracking/verbose 0 
/gate/generator/verbose 0 
/gate/source/verbose 0 
/run/particle/verbose 0 

/gate/run/initialize
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/source/addSource electron_beam gps
/gate/source/electron_beam/gps/particle gamma 
/gate/source/electron_beam/gps/ene/type Mono


/gate/source/electron_beam/gps/ene/mono 0.028000 MeV 
/gate/source/electron_beam/gps/pos/centre 0 0 -63 cm 
/gate/source/electron_beam/gps/ang/type iso 
/gate/source/electron_beam/gps/ang/mintheta 0. deg 
/gate/source/electron_beam/gps/ang/maxtheta 0. deg 
/gate/source/electron_beam/gps/ang/minphi 89. deg 
/gate/source/electron_beam/gps/ang/maxphi 90. deg 
/gate/source/electron_beam/gps/pos/type Plane
/gate/source/electron_beam/gps/pos/shape Circle
/gate/source/electron_beam/gps/pos/radius 0.707 cm

/gate/application/setTotalNumberOfPrimaries 2e9 
/gate/application/start 

